Module Project
    Sub Main()
        Dim threeLetterWords As String() = {"ace", "ace", "aha", "aid", "ail", "aim", "air", "ale", "and", "and", "any", "ape", "are", "ark", "arm", "art", "ash", "awe", "bad", "bee", "beg", "bet", "bid", "big", "boa", "bot", "boy", "but", "can", "cay", "cel", "cow", "cub", "cup", "dad", "deb", "did", "dot", "eve", "fit", "fur", "gal", "gap", "gay", "gel", "gig", "git", "god", "got", "gym", "hay", "hey", "his", "how", "ink", "inn", "kit", "lab", "lap", "led", "max", "mid", "mid", "mix", "mix", "mod", "mod", "mum", "nut", "one", "one", "pay", "pen", "pop", "ran", "rat", "rep", "row", "run", "sad", "say", "see", "shy", "sin", "sir", "spa", "sub", "tad", "tan", "tea", "ten", "the", "tie", "use", "vat", "vet", "web", "why", "yes", "yet"}
        Dim fourletterWords As String() = {"aids", "akin", "ally", "amid", "amps", "baby", "bark", "beam", "bend", "bend", "bike", "bird", "bird", "bite", "bolt", "bout", "burn", "cops", "core", "cubs", "dark", "doll", "dome", "dose", "eats", "fade", "fame", "fast", "fate", "feed", "file", "flow", "foil", "full", "gang", "give", "glue", "goes", "head", "hear", "here", "info", "jail", "knew", "lack", "laws", "link", "logo", "make", "mark", "mark", "mats", "meal", "melt", "milk", "mode", "nine", "nope", "nope", "odor", "pack", "park", "plan", "polo", "pork", "pubs", "raid", "rent", "ripe", "rule", "side", "sins", "song", "spam", "span", "star", "stat", "talk", "tape", "temp", "thee", "thin", "ties", "tire", "toes", "toll", "tone", "tool", "tour", "trim", "uses", "view", "void", "wait", "ways", "went", "woke", "wood", "yard", "yarn"}
        Dim fiveLetterWords As String() = {"abuse", "adult", "adult", "agent", "align", "alive", "allow", "amend", "angry", "angry", "ankle", "badge", "basis", "beats", "began", "begin", "bleed", "boats", "bones", "brake", "brick", "broke", "brown", "buddy", "calls", "cargo", "cases", "chain", "chain", "chest", "climb", "clubs", "cocoa", "cough", "count", "crank", "cruel", "cubic", "dated", "dates", "decor", "downs", "downs", "drone", "drove", "ducks", "elect", "error", "facts", "fares", "farms", "fault", "ferry", "files", "finds", "finds", "fixed", "flame", "flats", "flesh", "flour", "fully", "fully", "green", "grown", "habit", "kinda", "likes", "logic", "loved", "lower", "mouth", "moved", "never", "niche", "niche", "niche", "novel", "peers", "piece", "price", "price", "query", "radio", "right", "serve", "share", "small", "smoke", "sorts", "spend", "suite", "teams", "their", "trees", "trump", "ultra", "wires", "yards", "young"}


        Console.ReadKey()
    End Sub
End Module
